openapi: "3.0.2"
info:
  title: Documentation Rest API Learn with GOLANG
  version: "1.0"
servers:
  - url: https://localhost:3000/api/
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
