openapi: "3.0.2"
info:
  title: Documentation Rest API Learn with GOLANG
  version: "1.0"
servers:
  - url: https://localhost:3000/api/

paths:
  /authentication:
    post:
      tags:
        - "AUTH"
      summary: create token
      description: endopoint untuk melakukan authentication user akun agar bisa mengakses fitur lain
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: akeoneuefo
                password:
                  type: string
                  example: superone
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 128934
                      username:
                        type: string
                        example: akeoneuefo
                      name:
                        type: string
                        example: akeon osio
                  token:
                    type: string
                    example: "ijekn-9283keo3-983"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: wrong username or password
        "401":
          description: unautorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: your account not register yet
  /logout:
    delete:
      tags:
        - "AUTH"
      summary: delete token
      responses:
        "200":
          description: success delete token
        "400":
          description: fail to delete token
